apiVersion: v1
kind: Service
metadata:
  labels:
    app: demo2
  name: demo2
spec:
  ports:
  - name: 8081-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: demo2
  type: ClusterIP
status:
  loadBalancer: {}